const awards = [
  "Champion of Sitting Still",
  "Master of Overthinking",
  "World-Class Sock Organizer",
  "Supreme Ruler of Remote Controls",
  "Professional Procrastinator",
  "Gold Medal in Forgetting Names",
  "Certified Cereal Enthusiast",
  "Ambassador of Awkward Pauses",
  "Honorary Cloud Watcher",
  "Exalted Potato Chip Sommelier",
  "CEO of Pointless Trivia",
  "The Ultimate Blanket Fort Architect",
  "Legendary Queue Stand-In",
  "Elite Level Midnight Snacker",
  "Champion of Opening the Fridge and Staring",
  "Best in Class: Talking to Pets",
  "Knight of the Spilled Coffee",
  "Grandmaster of Losing Pens",
  "Lord of Unread Emails",
  "Master of Watching One Episode and Bingeing the Whole Series",
  "Top-Tier Grocery Aisle Wanderer",
  "Unrivaled Sock Hole Finder",
  "High Priest of Button Mashing",
  "Greatest Over-Explainer of Jokes",
  "Distinguished Over-Orderer of Takeout",
  "World-Class Random Fact Generator",
  "Noble Defender of the Snooze Button",
  "Most Likely to Trip Over Nothing",
  "Champion of Typing Without Looking at the Keyboard",
  "Hall of Fame Puddle Avoider",
  "Elite Expert in Saying ‘Oops’",
  "Most Likely to Forget Why They Entered a Room",
  "Supreme Commander of the Extra Pillow League",
  "Gold Star in Accidentally Replying to the Wrong Chat",
  "Master of Pressing the Elevator Button Repeatedly",
  "Record Holder for Longest ‘Umm’ in a Sentence",
  "Best at Almost Remembering Someone’s Birthday",
  "Grand Admiral of the Bedtime Scrolling Navy",
  "Honored Champion of Dropping Phones on Face",
  "Unparalleled Master of Saying ‘You Too’ at the Wrong Time",
  "Most Dedicated to Checking the Time but Forgetting Immediately",
  "Guardian of the Forgotten Shopping List",
  "Premier Awkward Goodbye Specialist",
  "World-Class Player of Imaginary Drums on the Steering Wheel",
  "Fastest at Looking Busy When the Boss Walks By",
  "Distinguished Hairbrush Microphone Performer",
  "Undisputed Champion of Finding the Worst Wi-Fi Spot",
  "Most Likely to Close Tabs and Regret It",
  "Renowned Advocate for Just Five More Minutes of Sleep",
  "Most Likely to Wave Back at Someone Waving at Someone Else",
  "Award-Winning Chair Swiveler",
  "Lifetime Achievement in Misplacing Glasses on Their Head",
  "Unrivaled Master of Getting Song Lyrics Wrong",
  "Knight of the Misspelled Texts",
  "Official Ambassador of Overpacking for a Weekend Trip",
  "Exalted Champion of Almost Spilling Drinks but Catching Them Last Second",
  "The Grand Archivist of Unfinished Projects",
  "Most Likely to Realize They Forgot to Take the Trash Out at Midnight",
  "Supreme Commander of Stubbing Toes on Furniture",
  "Champion of Watching Movie Trailers but Never the Movie",
  "Most Devoted to Hitting 'Remind Me Tomorrow' on Updates",
  "Lifetime Membership in the Accidental Double-Texters Club",
  "Professional ‘Did I Lock the Door?’ Overthinker",
  "The Undisputed Master of Overreacting to a Silent Phone Vibration",
  "Prestigious Award for Putting Something in a ‘Safe Place’ and Never Finding It Again",
  "Highly Decorated Master of Accidentally Making Things More Complicated",
  "Exalted Grandmaster of Speaking Before Thinking",
  "Honorary Member of the ‘One More Episode’ Society",
  "Top Performer in Forgetting Passwords Instantly",
  "Distinguished Couch Cushion Treasure Hunter",
  "Ambassador of Laughing at Own Jokes",
  "President of the Imaginary Arguments League",
  "Most Likely to Burn Their Tongue on Hot Food",
  "Eternal Champion of Losing Their Train of Thought Mid-Sentence",
  "Official Representative of Reading a Message but Forgetting to Reply",
  "World Champion in Checking the Mirror Twice Just to Be Sure",
  "The Greatest of All Time in Accidentally Turning on the Front Camera"
];

function randomValue(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function setAward() {
    document.getElementById("award").innerHTML = awards[randomValue(0,awards.length-1)];
}

setAward();