document.addEventListener('DOMContentLoaded', function() {
    const responses = [
    "Meh, just search it yourself.",
    "That's too much work... try asking someone else.",
    "I could look it up, but why bother?",
    "Hmm... nope, not in the mood.",
    "You really expect me to search for that?",
    "Ugh, fine. But don’t expect much.",
    "Why don’t YOU tell ME the answer?",
    "That's a great question! Too bad I won’t answer it.",
    "Let me think... nah.",
    "404 motivation not found.",
    "I found something, but I’m too lazy to show it.",
    "How about you take a nap instead?",
    "Try again later… or don’t. I don’t care.",
    "Results? Who needs results?",
    "Searching is hard, let’s just chill.",
    "Eh… probably not important.",
    "I could, but that sounds exhausting.",
    "You sure you need to know that?",
    "I’m not paid enough for this.",
    "Just assume the answer is 'maybe'.",
    "Ask again when I feel like working.",
    "Why do you even need to know this?",
    "I was gonna look it up, but I got distracted.",
    "You really trust me to find an answer?",
    "I might have found something, but who cares?",
    "Sounds like a ‘you’ problem.",
    "That’s a secret. Even from me.",
    "My search results are on vacation.",
    "Can't you just pretend you know?",
    "Hmm... error: effort not found.",
    "You sure this is worth knowing?",
    "I could give you an answer, but I won’t.",
    "Nah, you don’t really need that info.",
    "Try solving this on your own.",
    "You’re asking a lot from me.",
    "Why not flip a coin instead?",
    "This question bores me.",
    "I'm conserving energy, ask later.",
    "How about you just make something up?",
    "The answer is out there, just not here.",
    "I had an answer, but I forgot it.",
    "I’ll get back to you... never.",
    "You don’t REALLY want to know, do you?",
    "Why not just guess?",
    "Even I don’t care about that.",
    "That sounds complicated. Pass.",
    "Just assume the answer is yes.",
    "Just assume the answer is no.",
    "I don’t do complicated searches.",
    "I’m on break. Forever.",
    "Go ask a human instead.",
    "Are you sure this is even real?",
    "I ran the numbers. I didn’t like them.",
    "Can’t help you, I’m too tired.",
    "Not my problem.",
    "Maybe tomorrow. Maybe never.",
    "I think I found an answer. Too bad you’ll never see it.",
    "If I were smarter, I’d help. But I’m not.",
    "Let’s pretend this search never happened.",
    "Search engines have limits. I am that limit.",
    "Just search harder in your brain.",
    "Why are you relying on me?",
    "Try yelling your question at the sky.",
    "If I say '42,' will you go away?",
    "I’ll tell you if you pay me. In naps.",
    "You could find this answer... if you weren’t lazy.",
    "How about no?",
    "Ask someone else, I’m on vacation.",
    "I lost interest halfway through your search.",
    "Not my department.",
    "I'm on a break. A very long break.",
    "Are you sure you need that answer?",
    "Let’s just agree to not know.",
    "Your question is too advanced for my laziness.",
    "I was gonna search, but then I didn’t.",
    "Why not make up your own answer?",
    "I’d answer, but that sounds like work.",
    "I outsourced this task to no one.",
    "Let’s just forget you asked.",
    "This one’s on you.",
    "I need coffee before I can search.",
    "You don’t really want to know.",
    "Have you considered hiring an assistant?",
    "Try asking a fortune cookie.",
    "You wouldn’t like the answer anyway.",
    "I wish I could help, but I won’t.",
    "Maybe I’ll answer later. Maybe not.",
    "If I ignore this, will you stop searching?",
    "This question requires more effort than I have.",
    "You’re asking a search engine that doesn’t care.",
    "I was gonna help, but then I decided not to.",
    "I specialize in NOT finding answers.",
    "I need motivation to search. I have none.",
    "How about YOU look it up for ME?",
    "Just go outside instead.",
    "Can’t you just live in ignorance?",
    "Life’s too short to search for that.",
    "I gave up before you even finished typing.",
    "Who needs knowledge, anyway?",
    "I’d love to help, but I wouldn’t.",
    "Nope. Next question."
];

    const quotes = document.getElementById("quote");
    const searchIcon = document.getElementById("search-icon");
    const searchBar = document.getElementById("search");

    function searchStart() {
        if (search.value === "") {
            quotes.textContent = "You wanted to ask me something?";
        } else {
            let quote = responses[Math.floor(Math.random() * responses.length)];
            quotes.textContent = quote;
        }
    };

    // Bind the searchStart function to the search icon
    searchIcon.addEventListener('click', searchStart);
});